# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1laf_bBqu3TlmP40KWXHKC9jcjOhHKa6V
"""

File "/tmp/ipython-input-3701482107.py", line 9
    "
    ^
SyntaxError: unterminated string literal (detected at line 9)